### ISSUE TITLE
`ensure_installed`

### ISSUE THREAD

**Issue by princejoogie** [williamboman/mason.nvim#483] opened 2022-09-29 21:19 UTC
### I've searched open issues for similar requests

- [ ] Yes

### Is your feature request related to a problem? Please describe.

is it possible to have a `ensure_installed` option in config? basically defining certain lsps, linters, formatters to be automatically installed.

### Describe the solution you'd like

something like this:

```lua
require("mason").setup({
  ensure_isntalled = {
    lsp = {
      "typescript-language-server",
      "prisma-language-server",
      "eslint-lsp"
    },
    dap = {
      "node-debug2-adapter",
    },
    linter = {
      "eslint_d"
    },
    formatter = {
      "prettier"
    }
  }
})
```

**Comment by williamboman** [comment] 2022-10-02 21:00
I believe this is duplicate of #103

**Closed by williamboman** 2022-10-02 21:00 UTC
Labels: enhancement

**Comment by eduvj91** [comment] 2023-11-22 19:31
Dear @princejoogie, I have done the auto-installation of languages with a dependency of LSP, which attached its GitHub, and there it says how you can install it, only I have not found the way to organize them by, "LSP", "DAP", "LINTER" or "format", as requested. 

Let me know if you have been able to carry out these self-installations with this method and if you have been able to organize them as you want. Best regards.

https://github.com/williamboman/mason-lspconfig.nvim#configuration

```lua
require("mason-lspconfig").setup {
    ensure_installed = { "lua_ls", "rust_analyzer" },
}
```
