### ISSUE TITLE
lua error message when closing Mason on 

### ISSUE THREAD

**Issue by alexmaloteaux** [williamboman/mason.nvim#552] opened 2022-10-14 11:51 UTC
### Problem description

when closing Mason i have systematicallly an error lua message : 
```

Error executing vim.schedule lua callback: ...ck/packer/start/mason.nvim/lua/mason-core/ui/display.lua:495: Vim:E367: No such group: "--Deleted--"
stack traceback:
        [C]: in function 'nvim_del_augroup_by_id'
        ...ck/packer/start/mason.nvim/lua/mason-core/ui/display.lua:495: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
vim and Mason works without issue besides this message

### Neovim version (>= 0.7)

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

### Operating system/version

Linux amalo 5.15.73-1-lts #1 SMP Wed, 12 Oct 2022 10:21:34 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

error message

### Expected behavior

no error message

### Healthcheck output

```shell
none provided
```

**Comment by williamboman** [comment] 2022-10-14 12:48
Hello! Hm. Could you see if #553 (branch `fix/ui-augroup-del`) fixes this?

**Comment by alexmaloteaux** [comment] 2022-10-14 13:10
still the same , however it seems that just , launching nvim , then Mason and quitting it (with escape), doesn't immediately trigger the error message.
A minimum of "activity" is necessary, otherwise the error msg is not triggered.

Sorry for the poor description but i didnt found a pattern to have it 100% persistent :)
br

**Comment by williamboman** [comment] 2022-10-14 14:52
Which steps (from start to error) do you do to trigger this error?

**Comment by alexmaloteaux** [comment] 2022-10-14 15:13
launch Mason with :Mason
optionally do some activity like install/update/browse
then quit with ESC

the issue start randomly from first up to 10+ launch, from there appears "almost" permanently on each subsequent launch

**Comment by williamboman** [comment] 2023-02-07 20:01
I'm going to close this as there have not been any other reports regarding this, and I've been unable to reproduce.

**Closed by williamboman** 2023-02-07 20:01 UTC

**Comment by WuerfelDev** [comment] 2023-02-15 08:46
I experience the same problem, except the error is now in line 506.
It seems like I can reproduce it with **double-hitting** the ESC key
```
Error executing vim.schedule lua callback: ...ck/packer/start/mason.nvim/lua/mason-core/ui/display.lua:506: Vim:E367: No such group: "--Deleted--"
stack traceback:
        [C]: in function 'nvim_del_augroup_by_id'
        ...ck/packer/start/mason.nvim/lua/mason-core/ui/display.lua:506: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by alexmaloteaux** [comment] 2023-02-15 12:12
yes correct hitting 2 times esc trigger it for me each time

**Comment by WuerfelDev** [comment] 2023-02-20 12:49
I found this (https://www.johnhawthorn.com/2012/09/vi-escape-delays/) and noticed that my delay was caused by `tmux`.
Now the error still exists, but we avoid running into it.
