### ISSUE TITLE
Auto-install Packages (Other than LSP Servers)

### ISSUE THREAD

**Issue by CalebDW** [williamboman/mason.nvim#220] opened 2022-08-01 23:44 UTC
### Is your feature request related to a problem? Please describe.

Currently, `mason-lspconfig` will auto-install a list of servers with the `ensure_installed` and `automatic_installation` options. However, there is no method for auto-installing DAP servers, linters and formatters in `mason`.

### Describe the solution you'd like

Ideally, the same solution as what's currently in `mason-lspconfig`---I give `mason` a list of packages to install and it automatically installs them for me.

Alternatively, it might be worthwhile to move the automatic installation logic from `mason-lspconfig` to `mason`.

### Describe potential alternatives you've considered

Manually installing the packages through the `:Mason` interface.

**Comment by gutyina70** [comment] 2022-08-02 09:13
There's a seperate plugin for auto installing mason packages, but I'd like to see this built into mason too.
https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim

**Comment by gutyina70** [comment] 2022-08-02 09:19
Duplicate of https://github.com/williamboman/mason.nvim/issues/103.

**Comment by williamboman** [comment] 2022-08-02 12:26
Hello! Yep duplicate of #103

**Closed by williamboman** 2022-08-02 12:26 UTC
Labels: enhancement
