### ISSUE TITLE
[New package]: metals

### ISSUE THREAD

**Issue by dave-kennedy** [williamboman/mason.nvim#391] opened 2022-09-07 14:06 UTC
### Package name

metals

### Package homepage

https://scalameta.org/metals/

### Languages

java

**Comment by williambotman** [comment] 2022-09-07 14:06
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment] 2022-09-07 17:47
Duplicate of #369

**Closed by williamboman** 2022-09-07 17:47 UTC
Labels: new-package-request
