### ISSUE TITLE
Add ensure_installed in mason.nvim

### ISSUE THREAD

**Issue by LevyCory** [williamboman/mason.nvim#1338] opened 2023-06-04 15:17 UTC
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

In `mason-lspconfig` we have the option to pass `ensure_installed`, a list of packages that mason will install automatically when the config is executed. I'd like to have the same feature for Mason to ensure non-lsp dependencies are installed.

### Describe potential alternatives you've considered

I've seen people use `null-ls` to get this functionality from `mason-lspconfig` but it seems like a workaround and not a solution.

**Comment by emmanueltouzery** [comment] 2023-06-23 20:54
probably should be closed as duplicate of https://github.com/williamboman/mason.nvim/issues/103 https://github.com/williamboman/mason.nvim/issues/130 or https://github.com/williamboman/mason.nvim/issues/226 although I'd welcome this feature as well.

**Comment by williamboman** [comment] 2023-06-28 20:17
Closing as duplicate. I'll also add that this feature would be trivial to add, but I'm trying to ensure it fits well with future roadmap and that it won't suffer the penalties that'd be involved due having to load significantly more code during setup). This can easily be added to your own config, for example:

- https://github.com/williamboman/mason.nvim/issues/130#issuecomment-1217773757
- https://github.com/williamboman/mason.nvim/issues/1309#issuecomment-1555018732

**Closed by williamboman** 2023-06-28 20:17 UTC
Labels: enhancement
