### ISSUE TITLE
Keep getting `Cannot find package "\"eslint\""` error in MasonLog

### ISSUE THREAD

**Issue by xfzv** [williamboman/mason.nvim#1020] opened 2023-02-21 10:18 UTC
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

After updating to https://github.com/williamboman/mason.nvim/commit/b8a6632a0f2d263199d5d480ca85477fe0f414ab, I keep getting the following error in Mason log. It's printed as soon as I open Neovim.

```
[ERROR Tue 21 Feb 2023 10:39:00 AM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"eslint\"".
```

- `mason.lua`:

```lua
return {
	"williamboman/mason.nvim",
	config = function()
		require("mason").setup({
			ui = {
				icons = {
					package_installed = "✓",
					package_pending = "➜",
					package_uninstalled = "✗",
				},
			},
		})
	end,
}
```

- `mason-null-ls.lua`:

```lua
return {
	"jay-babu/mason-null-ls.nvim",
	config = function()
		require("mason-null-ls").setup({
			automatic_installation = true,
			ensure_installed = {
				"beautysh",
				"clang_format",
				"eslint_d",
				"jsonlint",
				"prettier",
				"shellcheck",
				"shfmt",
				"stylua",
				"yamlfmt",
				"yamllint",
			},
		})
	end,
}
```

I tried to delete `~/.local/share/nvim/mason/bin/eslint_d` and `~/.local/share/nvim/mason/packages/eslint_d` but it doesn't make any difference after `eslint_d` is reinstalled automatically.

Any idea? Thanks.

### Expected behavior

The error isn't printed

### Steps to reproduce

1. Update to https://github.com/williamboman/mason.nvim/commit/b8a6632a0f2d263199d5d480ca85477fe0f414ab
2. Use the config mentioned above for `mason` and `mason-null-ls`
3.  Open Neovim and run `:MasonLog`: the error mentioned above is printed every time in Mason log

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system/version

 ```
Linux archlinux 6.2.0-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 20 Feb 2023 22:05:57 +0000 x86_64 GNU/Linux
```

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.20.1 linux/amd64`
  - OK: **cargo**: `cargo 1.67.1`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v19.6.1`
  - OK: **python3**: `Python 3.10.9`
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.88.1-DEV (x86_64-pc-linux-gnu) libcurl/7.88.1-DEV OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: Tue 21 Feb 2023 11:38:56 AM CET.
```

**Comment by williamboman** [comment] 2023-02-21 10:24
Hey! See https://github.com/williamboman/mason.nvim/discussions/1017#discussioncomment-5058075

**Comment by williamboman** [comment] 2023-02-21 11:46
And do you set up mason.nvim anywhere?

**Comment by williamboman** [comment] 2023-02-21 12:32
I'm not familiar with lazy.nvim, have you checked that they execute in the right order (mason -> mason-lspconfig -> lspconfig)?

**Comment by ls-devs** [comment] 2023-02-21 13:43
Hi,
I have the same problem with all my configuration since #1016 .
See : 
![mason](https://user-images.githubusercontent.com/58638832/220361725-52f34e09-0bf9-49a9-98f2-5ca64f82a2ce.png)


MasonLog : 
```
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"html-lsp\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"lemminx\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"css-lsp\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cssmodules-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"emmet-ls\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"typescript-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"vue-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"tailwindcss-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"prisma-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"json-lsp\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"intelephense\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"sqlls\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"yaml-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"dockerfile-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"docker-compose-language-service\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"marksman\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"rust-analyzer\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"pyright\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"clangd\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cmake-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"lua-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"haskell-language-server\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"clangd\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"black\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"stylua\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"xmlformatter\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"luacheck\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"eslint_d\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"prettierd\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"rustfmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"shellharden\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"prismaFmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cmakelang\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"markdownlint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"yamllint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"yamlfmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"jsonlint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"jq\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"phpcs\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"php-cs-fixer\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"proselint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"refactoring\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"hadolint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"fourmolu\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"clang-format\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cpplint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"eslint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"luacheck\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"eslint_d\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cpplint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cmake-lint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"yamllint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"jsonlint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"hadolint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"phpcs\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"markdownlint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"stylua\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"fourmolu\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"prettierd\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"rustfmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"shellharden\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"prismaFmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"clang-format\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cmakelang\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"yamlfmt\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"xmlformat\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"jq\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"php-cs-fixer\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"black\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"refactoring\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"proselint\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"debugpy\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"node-debug2-adapter\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"php-debug-adapter\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"codelldb\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"cpptools\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"js-debug-adapter\"".
[ERROR Tue 21 Feb 2023 02:42:30 PM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"bash-debug-adapter\"".
```

**Comment by williamboman** [comment] 2023-02-21 15:54
I'm afraid I can't give support for how to set things up using lazy.nvim because I've never used it. The problem is rather simple though, Mason needs to be set up first. @ls-devs your dependency structure seems a bit problematic, mason.nvim doesn't have any dependencies, it's the other way around.

**Comment by ls-devs** [comment] 2023-02-21 16:05
> I'm afraid I can't give support for how to set things up using lazy.nvim because I've never used it. The problem is rather simple though, Mason needs to be set up first. @ls-devs your dependency structure seems a bit problematic, mason.nvim doesn't have any dependencies, it's the other way around.

@williamboman 
I use it this way because when I load `Mason` I want `mason-lspconfig`, `mason-null-ls` & `mason-nvim-dap` to be loaded too.
This is the way it works with Lazy. So it first load Mason, then the others.

The problem is here since last plugins update, and I can't figure out wich update is causing problem, if this is yours or Lazy update.

As I said, I don't think the order here is important, since it was working fine for me until now.

**Comment by williamboman** [comment] 2023-02-21 16:21
From what I can tell so far, there's no issue with either mason.nvim or lazy.nvim. The plugins are simply being set up in the wrong order. The reason it may have worked before was because the registry was hard-coded - this was decoupled in #1016. Interacting with `mason-registry` before setting up mason was never supported, so the fact that it may have worked before was more incidental than intentional.

Just to illustrate what the change did: [this is what the `:Mason` window looks like with no registries configured](https://user-images.githubusercontent.com/6705160/220398977-9eee62ff-a870-4dcf-a4cd-9feeac1078a2.png). Setting up Mason (i.e. `require("mason").setup {}`) will enable the core registries [by default](https://github.com/williamboman/mason.nvim/blob/4b82b711cb58e7f2dae75963cc960f5bbddcad8b/lua/mason/settings.lua#L17-L21), giving access to the set of packages you expect to exist.

> EDIT 2 :
> Please see the loading order of the plugins here

I'm not sure how to interpret this image, and again I'm unable to help with lazy.nvim-specific settings. All I can say is to make sure to set up Mason before any of the `mason-*` plugins & `lspconfig`. Ideally, Mason should be one of the very first plugins you set up.

I'll close this here because I won't be able to offer any more help on the topic, if it turns out to indeed be some issue with Mason itself let's reopen.

**Closed as completed by williamboman** 2023-02-21 16:21 UTC

**Comment by williamboman** [comment] 2023-02-21 19:13
Nice @lv-devs, thanks for sharing the solution! I hope to get around to checking out lazy.nvim myself soon.

@xfzv You probably don't want to defer setting up Mason until the `:Mason` command is executed. Mason does some important things during setup such as setting up the `PATH`.

**Comment by ls-devs** [comment] 2023-02-21 20:41
> > @williamboman You were right. It was plugins order problem. Managed to make it works this way, if it can help :
> > ```lua
> >   {
> >     cmd = "Mason",
> >     "williamboman/mason-lspconfig.nvim",
> >     config = require("ls-devs.plugins.mason-lspconfig").config,
> >     dependencies = {
> >       {
> >         "williamboman/mason.nvim",
> >         config = require("ls-devs.plugins.mason").config,
> >       },
> >       {
> >         "jay-babu/mason-null-ls.nvim",
> >         config = require("ls-devs.plugins.mason-null-ls").config,
> >       },
> >       {
> >         "jay-babu/mason-nvim-dap.nvim",
> >         config = require("ls-devs.plugins.mason-nvim-dap").config,
> >       },
> >     },
> >   },
> > ```
> 
> Thank you for the suggestion. I'm still getting the error after any `Mason` command (because of `cmd = "Mason"`) with this order. ~May I ask how you load `neovim/nvim-lspconfig` now?~
> 
> Edit: I'll take a look at your dots.

I don't setup lspconfig mysel, I use `lsp-zero` for that.

Here's how I setup lsp-zero (but yes, feel free to take a look at my dots !)
```lua
local M = {}

M.config = function()
  require("lspconfig.ui.windows").default_options.border = "rounded"

  local lsp = require("lsp-zero")

  lsp.preset("recommended")

  vim.diagnostic.config({
    virtual_text = false,
    update_in_insert = false,
    underline = true,
    severity_sort = true,
    float = {
      focusable = true,
      style = "minmal",
      border = "rounded",
      source = "always",
      header = "",
      prefix = "",
    },
  })

  lsp.preset("lsp-compe")

  lsp.on_attach(function(client, bufnr)
    require("lsp-inlayhints").on_attach(client, bufnr)
    if client.server_capabilities["documentSymbolProvider"] then
      require("nvim-navic").attach(client, bufnr)
    end
  end)

  local get_servers = require("mason-lspconfig").get_installed_servers
  for _, server in pairs(get_servers()) do
    local config_exists, config = pcall(require, "ls-devs.lsp.settings." .. server)
    if config_exists then
      lsp.configure(server, config)
    end
  end

  lsp.nvim_workspace()

  lsp.skip_server_setup({ "rust_analyzer" })

  lsp.setup()

  -- Autocmd for stopping eslint_d & prettier_d when leaving nvim
  vim.cmd("autocmd ExitPre *.jsx,*.tsx,*.vue,*.js,*.ts silent! !eslint_d stop")
  vim.cmd("autocmd ExitPre *.jsx,*.tsx,*.vue,*.js,*.ts silent! !prettierd stop")
end

return M
```

@williamboman  You welcome :)

**Comment by ls-devs** [comment] 2023-02-22 10:34
> I finally found the cause of the error I had (`...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "\"eslint\"".`).
> 
> Turns out it wasn't related to plugins loading order.
> 
> I'm using [jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) with the following config:
> 
> ```lua
> return {
> 	"jose-elias-alvarez/null-ls.nvim",
> 	config = function()
> 		local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
> 		local formatting = require("null-ls").builtins.formatting
> 		local diagnostics = require("null-ls").builtins.diagnostics
> 
> 		require("null-ls").setup({
> 			sources = {
> 				formatting.beautysh.with({
> 					filetypes = { "zsh" },
> 				}),
> 				formatting.clang_format,
> 				formatting.prettier.with({
> 					filetypes = { "html", "json", "markdown", "scss", "css", "typescript", "rasi" },
> 				}),
> 				formatting.shfmt,
> 				formatting.stylua,
> 				formatting.yamlfmt,
> 				diagnostics.eslint_d,
> 				diagnostics.jsonlint,
> 				diagnostics.yamllint,
> 			},
> 			on_attach = function(current_client, bufnr)
> 				if current_client.supports_method("textDocument/formatting") then
> 					vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
> 					vim.api.nvim_create_autocmd("BufWritePre", {
> 						group = augroup,
> 						buffer = bufnr,
> 						callback = function()
> 							vim.lsp.buf.format({
> 								filter = function(client)
> 									return client.name == "null-ls"
> 								end,
> 								bufnr = bufnr,
> 							})
> 						end,
> 					})
> 				end
> 			end,
> 		})
> 	end,
> }
> ```
> 
> The error is no longer printed in Mason Log if I disable `diagnostics.eslint_d,`.
> 
> @williamboman any idea why this one specifically triggers an error and not the other formatting/diagnostics?

Have you installed eslint_d with mason ?

**Comment by ls-devs** [comment] 2023-02-22 10:37
Are you using `mason-null-ls` ?

**Comment by ls-devs** [comment] 2023-02-22 10:44
Are you sure you are loading your plugins in the right order ? As I posted ?

```lua
  {
    cmd = "Mason",
    "williamboman/mason-lspconfig.nvim",
    config = require("ls-devs.plugins.mason-lspconfig").config,
    dependencies = {
      {
        "jay-babu/mason-null-ls.nvim",
        config = require("ls-devs.plugins.mason-null-ls").config,
      },
      {
        "jay-babu/mason-nvim-dap.nvim",
        config = require("ls-devs.plugins.mason-nvim-dap").config,
      },
      {
        "williamboman/mason.nvim",
        config = require("ls-devs.plugins.mason").config,
      },
    },
  },
```

**Comment by ls-devs** [comment] 2023-02-23 07:20
> > Are you sure you are loading your plugins in the right order ? As I posted ?
> > ```lua
> >   {
> >     cmd = "Mason",
> >     "williamboman/mason-lspconfig.nvim",
> >     config = require("ls-devs.plugins.mason-lspconfig").config,
> >     dependencies = {
> >       {
> >         "jay-babu/mason-null-ls.nvim",
> >         config = require("ls-devs.plugins.mason-null-ls").config,
> >       },
> >       {
> >         "jay-babu/mason-nvim-dap.nvim",
> >         config = require("ls-devs.plugins.mason-nvim-dap").config,
> >       },
> >       {
> >         "williamboman/mason.nvim",
> >         config = require("ls-devs.plugins.mason").config,
> >       },
> >     },
> >   },
> > ```
> 
> Yes, that's what I tried in the first place but the error is still triggered unless I disable `eslint_d` in `null-ls`.

I'm affraid I can't help you here since I don't know how to reproduce your issue. Sorry.

**Comment by ls-devs** [comment] 2023-10-18 10:59
Hi, 
Sorry to bother with a really old issue but I found a real answer for the problem.
Tbh, with the old answer I still had some package not found warnings for null-ls packages.

But today I found out I have no more warnings using this config : 
```lua
  -- Mason & Managers
  {
    "williamboman/mason-lspconfig.nvim",
    config = require("ls-devs.plugins.mason-lspconfig").config,
    event = "VimEnter",
    dependencies = {
      {
        "jay-babu/mason-null-ls.nvim",
        config = require("ls-devs.plugins.mason-null-ls").config,
        -- Formatter
        {
          "nvimtools/none-ls.nvim",
          event = "BufReadPre",
          config = require("ls-devs.plugins.null-ls").config,
        },
      },
      {
        "jay-babu/mason-nvim-dap.nvim",
        config = require("ls-devs.plugins.mason-nvim-dap").config,
      },
      {
        "williamboman/mason.nvim",
        config = require("ls-devs.plugins.mason").config,
      },
    },
  },
```

If it can help.
